project:
  type: book

book:
  title: 【生物】信息、科技、和图像分析（2）
  subtitle: 内容是个人的，因此是片面的
  author: iAmHealthy
  date: last-modified
  favicon: images/2026-03-10_swan-inverted-reflection.png
  page-navigation: true
  cover-image: images/2026-03-10_swan-inverted-reflection.png
  page-footer: 
    center: "Copyright 2026 iAmHealthy"
    background: dark
    border: true

  chapters:
    
    - index.qmd

    - part: R
      chapters:
        - 2026-03-02_新疆生产建设兵团的分布.qmd
        - 2026-03-26_quote-of-the-day.qmd

    - part: QuPath
      chapters: 
        - 2026-03-25_mrxs-to-ome.qmd      

    - part: R & QuPath
      chapters:
        - 2026-03-09_swan.qmd
        - 2026-03-14_qupath-release-history-and-size.qmd
        - 2026-03-23_qupath-snapshot.qmd

    - part: 技术相关
      chapters:
        - 2026-03-04_切片染色方法.qmd

    - part: 图像分析

    - part: 科学相关

    - part: 生物图像分析流程

    - part: 其它
      chapters:
        - 给我买杯茶.qmd

bibliography: references.bib
csl: science.csl

highlight-style: pygments

format:
  html:
    theme:
      light: Sandstone
      dark: Solar
    code-copy: true
    number-depth: 1



